<?php


// All countries
// length 252
$countries_list = [
    ["continent" => "Asia", "name" => "L'Afghanistan", "code" => "AF"],
    ["continent" => "Europe", "name" => "Iles Aland", "code" => "AX"],
    ["continent" => "Europe", "name" => "Albanie", "code" => "AL"],
    ["continent" => "Africa", "name" => "Algérie", "code" => "DZ"],
    ["continent" => "Oceania", "name" => "Samoa américaines", "code" => "AS"],
    ["continent" => "Europe", "name" => "Andorre", "code" => "AD"],
    ["continent" => "Africa", "name" => "L'Angola", "code" => "AO"],
    ["continent" => "North America", "name" => "Anguilla", "code" => "AI"],
    ["continent" => "Antarctica", "name" => "Antarctique", "code" => "AQ"],
    ["continent" => "North America", "name" => "Antigua-et-Barbuda", "code" => "AG"],
    ["continent" => "South America", "name" => "Argentine", "code" => "AR"],
    ["continent" => "Asia", "name" => "Arménie", "code" => "AM"],
    ["continent" => "North America", "name" => "Aruba", "code" => "AW"],
    ["continent" => "Oceania", "name" => "Australie", "code" => "AU"],
    ["continent" => "Europe", "name" => "L'Autriche", "code" => "AT"],
    ["continent" => "Asia", "name" => "Azerbaïdjan", "code" => "AZ"],
    ["continent" => "North America", "name" => "Bahamas", "code" => "BS"],
    ["continent" => "Asia", "name" => "Bahreïn", "code" => "BH"],
    ["continent" => "Asia", "name" => "Bangladesh", "code" => "BD"],
    ["continent" => "North America", "name" => "Barbade", "code" => "BB"],
    ["continent" => "Europe", "name" => "Biélorussie", "code" => "BY"],
    ["continent" => "Europe", "name" => "Belgique", "code" => "BE"],
    ["continent" => "North America", "name" => "Belize", "code" => "BZ"],
    ["continent" => "Africa", "name" => "Bénin", "code" => "BJ"],
    ["continent" => "North America", "name" => "Bermudes", "code" => "BM"],
    ["continent" => "Asia", "name" => "Bhoutan", "code" => "BT"],
    ["continent" => "South America", "name" => "Bolivie", "code" => "BO"],
    ["continent" => "North America", "name" => "Bonaire, Saint-Eustache et Saba", "code" => "BQ"],
    ["continent" => "Europe", "name" => "Bosnie Herzégovine", "code" => "BA"],
    ["continent" => "Africa", "name" => "Botswana", "code" => "BW"],
    ["continent" => "Antarctica", "name" => "Île Bouvet", "code" => "BV"],
    ["continent" => "South America", "name" => "Brésil", "code" => "BR"],
    ["continent" => "Asia", "name" => "Territoire britannique de l'océan Indien", "code" => "IO"],
    ["continent" => "Asia", "name" => "Brunei Darussalam", "code" => "BN"],
    ["continent" => "Europe", "name" => "Bulgarie", "code" => "BG"],
    ["continent" => "Africa", "name" => "Burkina Faso", "code" => "BF"],
    ["continent" => "Africa", "name" => "Burundi", "code" => "BI"],
    ["continent" => "Asia", "name" => "Cambodge", "code" => "KH"],
    ["continent" => "Africa", "name" => "Cameroun", "code" => "CM"],
    ["continent" => "North America", "name" => "Canada", "code" => "CA"],
    ["continent" => "Africa", "name" => "Cap-Vert", "code" => "CV"],
    ["continent" => "North America", "name" => "Îles Caïmans", "code" => "KY"],
    ["continent" => "Africa", "name" => "République centrafricaine", "code" => "CF"],
    ["continent" => "Africa", "name" => "Tchad", "code" => "TD"],
    ["continent" => "South America", "name" => "Chili", "code" => "CL"],
    ["continent" => "Asia", "name" => "Chine", "code" => "CN"],
    ["continent" => "Asia", "name" => "L'île de noël", "code" => "CX"],
    ["continent" => "Asia", "name" => "Îles Cocos (Keeling)", "code" => "CC"],
    ["continent" => "South America", "name" => "Colombie", "code" => "CO"],
    ["continent" => "Africa", "name" => "Comores", "code" => "KM"],
    ["continent" => "Africa", "name" => "Congo", "code" => "CG"],
    ["continent" => "Africa", "name" => "Congo, République démocratique du Congo", "code" => "CD"],
    ["continent" => "Oceania", "name" => "les Îles Cook", "code" => "CK"],
    ["continent" => "North America", "name" => "Costa Rica", "code" => "CR"],
    ["continent" => "Africa", "name" => "Côte d'Ivoire", "code" => "CI"],
    ["continent" => "Europe", "name" => "Croatie", "code" => "HR"],
    ["continent" => "North America", "name" => "Cuba", "code" => "CU"],
    ["continent" => "North America", "name" => "Curacao", "code" => "CW"],
    ["continent" => "Asia", "name" => "Chypre", "code" => "CY"],
    ["continent" => "Europe", "name" => "République Tchèque", "code" => "CZ"],
    ["continent" => "Europe", "name" => "Danemark", "code" => "DK"],
    ["continent" => "Africa", "name" => "Djibouti", "code" => "DJ"],
    ["continent" => "North America", "name" => "Dominique", "code" => "DM"],
    ["continent" => "North America", "name" => "République dominicaine", "code" => "DO"],
    ["continent" => "South America", "name" => "Equateur", "code" => "EC"],
    ["continent" => "Africa", "name" => "Egypte", "code" => "EG"],
    ["continent" => "North America", "name" => "Le Salvador", "code" => "SV"],
    ["continent" => "Africa", "name" => "Guinée Équatoriale", "code" => "GQ"],
    ["continent" => "Africa", "name" => "Érythrée", "code" => "ER"],
    ["continent" => "Europe", "name" => "Estonie", "code" => "EE"],
    ["continent" => "Africa", "name" => "Ethiopie", "code" => "ET"],
    ["continent" => "South America", "name" => "Îles Falkland (Malvinas)", "code" => "FK"],
    ["continent" => "Europe", "name" => "Îles Féroé", "code" => "FO"],
    ["continent" => "Oceania", "name" => "Fidji", "code" => "FJ"],
    ["continent" => "Europe", "name" => "Finlande", "code" => "FI"],
    ["continent" => "Europe", "name" => "France", "code" => "FR"],
    ["continent" => "South America", "name" => "Guyane Française", "code" => "GF"],
    ["continent" => "Oceania", "name" => "Polynésie française", "code" => "PF"],
    ["continent" => "Antarctica", "name" => "Terres australes françaises", "code" => "TF"],
    ["continent" => "Africa", "name" => "Gabon", "code" => "GA"],
    ["continent" => "Africa", "name" => "Gambie", "code" => "GM"],
    ["continent" => "Asia", "name" => "Géorgie", "code" => "GE"],
    ["continent" => "Europe", "name" => "Allemagne", "code" => "DE"],
    ["continent" => "Africa", "name" => "Ghana", "code" => "GH"],
    ["continent" => "Europe", "name" => "Gibraltar", "code" => "GI"],
    ["continent" => "Europe", "name" => "Grèce", "code" => "GR"],
    ["continent" => "North America", "name" => "Groenland", "code" => "GL"],
    ["continent" => "North America", "name" => "Grenade", "code" => "GD"],
    ["continent" => "North America", "name" => "Guadeloupe", "code" => "GP"],
    ["continent" => "Oceania", "name" => "Guam", "code" => "GU"],
    ["continent" => "North America", "name" => "Guatemala", "code" => "GT"],
    ["continent" => "Europe", "name" => "Guernesey", "code" => "GG"],
    ["continent" => "Africa", "name" => "Guinée", "code" => "GN"],
    ["continent" => "Africa", "name" => "Guinée-Bissau", "code" => "GW"],
    ["continent" => "South America", "name" => "Guyane", "code" => "GY"],
    ["continent" => "North America", "name" => "Haïti", "code" => "HT"],
    ["continent" => "Antarctica", "name" => "Îles Heard et McDonald", "code" => "HM"],
    ["continent" => "Europe", "name" => "Saint-Siège (État de la Cité du Vatican)", "code" => "VA"],
    ["continent" => "North America", "name" => "Honduras", "code" => "HN"],
    ["continent" => "Asia", "name" => "Hong Kong", "code" => "HK"],
    ["continent" => "Europe", "name" => "Hongrie", "code" => "HU"],
    ["continent" => "Europe", "name" => "Islande", "code" => "IS"],
    ["continent" => "Asia", "name" => "Inde", "code" => "IN"],
    ["continent" => "Asia", "name" => "Indonésie", "code" => "ID"],
    ["continent" => "Asia", "name" => "Iran (République islamique d", "code" => "IR"],
    ["continent" => "Asia", "name" => "Irak", "code" => "IQ"],
    ["continent" => "Europe", "name" => "Irlande", "code" => "IE"],
    ["continent" => "Europe", "name" => "île de Man", "code" => "IM"],
    ["continent" => "Asia", "name" => "Israël", "code" => "IL"],
    ["continent" => "Europe", "name" => "Italie", "code" => "IT"],
    ["continent" => "North America", "name" => "Jamaïque", "code" => "JM"],
    ["continent" => "Asia", "name" => "Japon", "code" => "JP"],
    ["continent" => "Europe", "name" => "Jersey", "code" => "JE"],
    ["continent" => "Asia", "name" => "Jordan", "code" => "JO"],
    ["continent" => "Asia", "name" => "Kazakhstan", "code" => "KZ"],
    ["continent" => "Africa", "name" => "Kenya", "code" => "KE"],
    ["continent" => "Oceania", "name" => "Kiribati", "code" => "KI"],
    ["continent" => "Asia", "name" => "République populaire démocratique de Corée", "code" => "KP"],
    ["continent" => "Asia", "name" => "Corée, République de", "code" => "KR"],
    ["continent" => "Europe", "name" => "Kosovo", "code" => "XK"],
    ["continent" => "Asia", "name" => "Koweit", "code" => "KW"],
    ["continent" => "Asia", "name" => "Kirghizistan", "code" => "KG"],
    ["continent" => "Asia", "name" => "République démocratique populaire lao", "code" => "LA"],
    ["continent" => "Europe", "name" => "Lettonie", "code" => "LV"],
    ["continent" => "Asia", "name" => "Liban", "code" => "LB"],
    ["continent" => "Africa", "name" => "Lesotho", "code" => "LS"],
    ["continent" => "Africa", "name" => "Libéria", "code" => "LR"],
    ["continent" => "Africa", "name" => "Jamahiriya arabe libyenne", "code" => "LY"],
    ["continent" => "Europe", "name" => "Liechtenstein", "code" => "LI"],
    ["continent" => "Europe", "name" => "Lituanie", "code" => "LT"],
    ["continent" => "Europe", "name" => "Luxembourg", "code" => "LU"],
    ["continent" => "Asia", "name" => "Macao", "code" => "MO"],
    ["continent" => "Europe", "name" => "Macédoine, ancienne République yougoslave de", "code" => "MK"],
    ["continent" => "Africa", "name" => "Madagascar", "code" => "MG"],
    ["continent" => "Africa", "name" => "Malawi", "code" => "MW"],
    ["continent" => "Asia", "name" => "Malaisie", "code" => "MY"],
    ["continent" => "Asia", "name" => "Maldives", "code" => "MV"],
    ["continent" => "Africa", "name" => "Mali", "code" => "ML"],
    ["continent" => "Europe", "name" => "Malte", "code" => "MT"],
    ["continent" => "Oceania", "name" => "Iles Marshall", "code" => "MH"],
    ["continent" => "North America", "name" => "Martinique", "code" => "MQ"],
    ["continent" => "Africa", "name" => "Mauritanie", "code" => "MR"],
    ["continent" => "Africa", "name" => "Ile Maurice", "code" => "MU"],
    ["continent" => "Africa", "name" => "Mayotte", "code" => "YT"],
    ["continent" => "North America", "name" => "Mexique", "code" => "MX"],
    ["continent" => "Oceania", "name" => "Micronésie, États fédérés de", "code" => "FM"],
    ["continent" => "Europe", "name" => "Moldova, République de", "code" => "MD"],
    ["continent" => "Europe", "name" => "Monaco", "code" => "MC"],
    ["continent" => "Asia", "name" => "Mongolie", "code" => "MN"],
    ["continent" => "Europe", "name" => "Monténégro", "code" => "ME"],
    ["continent" => "North America", "name" => "Montserrat", "code" => "MS"],
    ["continent" => "Africa", "name" => "Maroc", "code" => "MA"],
    ["continent" => "Africa", "name" => "Mozambique", "code" => "MZ"],
    ["continent" => "Asia", "name" => "Myanmar", "code" => "MM"],
    ["continent" => "Africa", "name" => "Namibie", "code" => "NA"],
    ["continent" => "Oceania", "name" => "Nauru", "code" => "NR"],
    ["continent" => "Asia", "name" => "Népal", "code" => "NP"],
    ["continent" => "Europe", "name" => "Pays-Bas", "code" => "NL"],
    ["continent" => "North America", "name" => "Antilles néerlandaises", "code" => "AN"],
    ["continent" => "Oceania", "name" => "Nouvelle Calédonie", "code" => "NC"],
    ["continent" => "Oceania", "name" => "Nouvelle-Zélande", "code" => "NZ"],
    ["continent" => "North America", "name" => "Nicaragua", "code" => "NI"],
    ["continent" => "Africa", "name" => "Niger", "code" => "NE"],
    ["continent" => "Africa", "name" => "Nigeria", "code" => "NG"],
    ["continent" => "Oceania", "name" => "Niue", "code" => "NU"],
    ["continent" => "Oceania", "name" => "l'ile de Norfolk", "code" => "NF"],
    ["continent" => "Oceania", "name" => "Îles Mariannes du Nord", "code" => "MP"],
    ["continent" => "Europe", "name" => "Norvège", "code" => "NO"],
    ["continent" => "Asia", "name" => "Oman", "code" => "OM"],
    ["continent" => "Asia", "name" => "Pakistan", "code" => "PK"],
    ["continent" => "Oceania", "name" => "Palau", "code" => "PW"],
    ["continent" => "Asia", "name" => "Territoire palestinien, occupé", "code" => "PS"],
    ["continent" => "North America", "name" => "Panama", "code" => "PA"],
    ["continent" => "Oceania", "name" => "Papouasie Nouvelle Guinée", "code" => "PG"],
    ["continent" => "South America", "name" => "Paraguay", "code" => "PY"],
    ["continent" => "South America", "name" => "Pérou", "code" => "PE"],
    ["continent" => "Asia", "name" => "Philippines", "code" => "PH"],
    ["continent" => "Oceania", "name" => "Pitcairn", "code" => "PN"],
    ["continent" => "Europe", "name" => "Pologne", "code" => "PL"],
    ["continent" => "Europe", "name" => "Le Portugal", "code" => "PT"],
    ["continent" => "North America", "name" => "Porto Rico", "code" => "PR"],
    ["continent" => "Asia", "name" => "Qatar", "code" => "QA"],
    ["continent" => "Africa", "name" => "Réunion", "code" => "RE"],
    ["continent" => "Europe", "name" => "Roumanie", "code" => "RO"],
    ["continent" => "Asia", "name" => "Fédération Russe", "code" => "RU"],
    ["continent" => "Africa", "name" => "Rwanda", "code" => "RW"],
    ["continent" => "North America", "name" => "Saint Barthélemy", "code" => "BL"],
    ["continent" => "Africa", "name" => "Sainte-Hélène", "code" => "SH"],
    ["continent" => "North America", "name" => "Saint-Christophe-et-Niévès", "code" => "KN"],
    ["continent" => "North America", "name" => "Sainte-Lucie", "code" => "LC"],
    ["continent" => "North America", "name" => "Saint Martin", "code" => "MF"],
    ["continent" => "North America", "name" => "Saint-Pierre-et-Miquelon", "code" => "PM"],
    ["continent" => "North America", "name" => "Saint-Vincent-et-les-Grenadines", "code" => "VC"],
    ["continent" => "Oceania", "name" => "Samoa", "code" => "WS"],
    ["continent" => "Europe", "name" => "Saint Marin", "code" => "SM"],
    ["continent" => "Africa", "name" => "Sao Tomé et Principe", "code" => "ST"],
    ["continent" => "Asia", "name" => "Arabie Saoudite", "code" => "SA"],
    ["continent" => "Africa", "name" => "Sénégal", "code" => "SN"],
    ["continent" => "Europe", "name" => "Serbie", "code" => "RS"],
    ["continent" => "Europe", "name" => "Serbie et Monténégro", "code" => "CS"],
    ["continent" => "Africa", "name" => "les Seychelles", "code" => "SC"],
    ["continent" => "Africa", "name" => "Sierra Leone", "code" => "SL"],
    ["continent" => "Asia", "name" => "Singapour", "code" => "SG"],
    ["continent" => "North America", "name" => "St Martin", "code" => "SX"],
    ["continent" => "Europe", "name" => "Slovaquie", "code" => "SK"],
    ["continent" => "Europe", "name" => "Slovénie", "code" => "SI"],
    ["continent" => "Oceania", "name" => "Les îles Salomon", "code" => "SB"],
    ["continent" => "Africa", "name" => "Somalie", "code" => "SO"],
    ["continent" => "Africa", "name" => "Afrique du Sud", "code" => "ZA"],
    ["continent" => "Antarctica", "name" => "Géorgie du Sud et îles Sandwich du Sud", "code" => "GS"],
    ["continent" => "Africa", "name" => "Soudan du sud", "code" => "SS"],
    ["continent" => "Europe", "name" => "Espagne", "code" => "ES"],
    ["continent" => "Asia", "name" => "Sri Lanka", "code" => "LK"],
    ["continent" => "Africa", "name" => "Soudan", "code" => "SD"],
    ["continent" => "South America", "name" => "Suriname", "code" => "SR"],
    ["continent" => "Europe", "name" => "Svalbard et Jan Mayen", "code" => "SJ"],
    ["continent" => "Africa", "name" => "Swaziland", "code" => "SZ"],
    ["continent" => "Europe", "name" => "Suède", "code" => "SE"],
    ["continent" => "Europe", "name" => "la Suisse", "code" => "CH"],
    ["continent" => "Asia", "name" => "République arabe syrienne", "code" => "SY"],
    ["continent" => "Asia", "name" => "Taiwan, Province de Chine", "code" => "TW"],
    ["continent" => "Asia", "name" => "Tadjikistan", "code" => "TJ"],
    ["continent" => "Africa", "name" => "Tanzanie, République-Unie de", "code" => "TZ"],
    ["continent" => "Asia", "name" => "Thaïlande", "code" => "TH"],
    ["continent" => "Asia", "name" => "Timor-Leste", "code" => "TL"],
    ["continent" => "Africa", "name" => "Aller", "code" => "TG"],
    ["continent" => "Oceania", "name" => "Tokelau", "code" => "TK"],
    ["continent" => "Oceania", "name" => "Tonga", "code" => "TO"],
    ["continent" => "North America", "name" => "Trinité-et-Tobago", "code" => "TT"],
    ["continent" => "Africa", "name" => "Tunisie", "code" => "TN"],
    ["continent" => "Asia", "name" => "Turquie", "code" => "TR"],
    ["continent" => "Asia", "name" => "Turkménistan", "code" => "TM"],
    ["continent" => "North America", "name" => "îles Turques-et-Caïques", "code" => "TC"],
    ["continent" => "Oceania", "name" => "Tuvalu", "code" => "TV"],
    ["continent" => "Africa", "name" => "Ouganda", "code" => "UG"],
    ["continent" => "Europe", "name" => "Ukraine", "code" => "UA"],
    ["continent" => "Asia", "name" => "Emirats Arabes Unis", "code" => "AE"],
    ["continent" => "Europe", "name" => "Royaume-Uni", "code" => "GB"],
    ["continent" => "North America", "name" => "États-Unis", "code" => "US"],
    ["continent" => "North America", "name" => "Îles mineures éloignées des États-Unis", "code" => "UM"],
    ["continent" => "South America", "name" => "Uruguay", "code" => "UY"],
    ["continent" => "Asia", "name" => "Ouzbékistan", "code" => "UZ"],
    ["continent" => "Oceania", "name" => "Vanuatu", "code" => "VU"],
    ["continent" => "South America", "name" => "Venezuela", "code" => "VE"],
    ["continent" => "Asia", "name" => "Viet Nam", "code" => "VN"],
    ["continent" => "North America", "name" => "Îles Vierges britanniques", "code" => "VG"],
    ["continent" => "North America", "name" => "Îles Vierges américaines, États-Unis", "code" => "VI"],
    ["continent" => "Oceania", "name" => "Wallis et Futuna", "code" => "WF"],
    ["continent" => "Africa", "name" => "Sahara occidental", "code" => "EH"],
    ["continent" => "Asia", "name" => "Yémen", "code" => "YE"],
    ["continent" => "Africa", "name" => "Zambie", "code" => "ZM"],
    ["continent" => "Africa", "name" => "Zimbabwe", "code" => "ZW"]
];

function listePays($key)
{
    return function ($a, $b) use ($key) {
        return strnatcmp($a[$key], $b[$key]);
    };
}
usort($countries_list, listePays('name'));

$continent='';
require_once('liste de pays.php');
